version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo "Building React application..."
      - npm run build

  artifacts:
    files:
      - '**/*'
    base-directory: build
    discard-paths: no