version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://www.taimoor-s3-bucket/
      - aws cloudfront create-invalidation --distribution-id E20QTQ8GCYQPDD --path "/\*"
