version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building React application..."
      - npm run build

  post_build:
    commands:
      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version
      - echo "Creating CloudFront invalidation..."
      - aws cloudfront create-invalidation --distribution-id E3PZ9CZKCIRUDC --paths "/*" --region us-east-1

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no
